import ar.unlam.edu.Cancion

import ar.unlam.edu.Lista

class BootStrap {

    def init = { servletContext ->
		
	// Canciones 
		def cancion1 = new Cancion(author: 'No te va a gustar', name:'Sin pena ni gloria', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (1).mp3', cancionOriginalId:1)
		cancion1.save(flush:true)
		def cancion2 = new Cancion(author: 'No te va a gustar', name:'Nada fue en vano', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (2).mp3', cancionOriginalId:2)
		cancion2.save(flush:true)
		def cancion3 = new Cancion(author: 'No te va a gustar', name:'A las nueve', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (3).mp3', cancionOriginalId:3)
		cancion3.save(flush:true)
		def cancion4 = new Cancion(author: 'No te va a gustar', name:'Como brillaba tu alma', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (4).mp3', cancionOriginalId:4)
		cancion4.save(flush:true)
		def cancion5 = new Cancion(author: 'No te va a gustar', name:'Tan lejos', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (5).mp3', cancionOriginalId:"5")
		cancion5.save(flush:true)
		def cancion6 = new Cancion(author: 'No te va a gustar', name:'Fuera de control', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (6).mp3', cancionOriginalId:"6")
		cancion6.save(flush:true)
		def cancion7 = new Cancion(author: 'No te va a gustar', name:'Una triste melodia', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (7).mp3', cancionOriginalId:"7")
		cancion7.save(flush:true)		
		def cancion8 = new Cancion(author: 'Pappo', name:'El tren de las 16', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (8).mp3', cancionOriginalId:"8")
		cancion8.save(flush:true)		
		def cancion9 = new Cancion(author: 'Rata blanca', name:'Mujer amante', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (9).mp3', cancionOriginalId:"9")
		cancion9.save(flush:true)
		def cancion10 = new Cancion(author: 'Sui generis', name:'Seminare', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (10).mp3', cancionOriginalId:"10")
		cancion10.save(flush:true)
		def cancion11 = new Cancion(author: 'Los pericos', name:'Nada que perder', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (11).mp3', cancionOriginalId:"11")
		cancion11.save(flush:true)
		def cancion12 = new Cancion(author: 'Vicentico', name:'Himno de mi corazon', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (12).mp3', cancionOriginalId:"12")
		cancion12.save(flush:true)
		def cancion13 = new Cancion(author: 'Viejas locas', name:'Me gustas mucho', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (13).mp3', cancionOriginalId:"13")
		cancion13.save(flush:true)
		def cancion14 = new Cancion(author: 'Los Fabulosos Cadillacs', name:'Vos sabes', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (14).mp3', cancionOriginalId:"14")
		cancion14.save(flush:true)
		def cancion15 = new Cancion(author: 'Spinetta', name:'El anillo del capitan beto', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (15).mp3', cancionOriginalId:"15")
		cancion15.save(flush:true)
		def cancion16 = new Cancion(author: 'Callejeros', name:'Ahogados de razon', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (16).mp3', cancionOriginalId:"16")
		cancion16.save(flush:true)
		def cancion17 = new Cancion(author: 'Dos minutos', name:'Ya no sos igual', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (17).mp3', cancionOriginalId:"17")
		cancion17.save(flush:true)
		def cancion18 = new Cancion(author: 'Autenticos decadentes', name:'No me importa el dinero', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (18).mp3', cancionOriginalId:"18")
		cancion18.save(flush:true)
		def cancion19 = new Cancion(author: 'Andres calamaro', name:'Flaca', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (19).mp3', cancionOriginalId:"19")
		cancion19.save(flush:true)
		def cancion20 = new Cancion(author: 'Calle 13', name:'Latinoamerica', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (20).mp3', cancionOriginalId:"20")
		cancion20.save(flush:true)
		def cancion21 = new Cancion(author: 'Callejeros', name:'¿Cuánto mas?', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (21).mp3', cancionOriginalId:"21")
		cancion21.save(flush:true)
		def cancion22 = new Cancion(author: 'Callejeros', name:'Creo', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (22).mp3', cancionOriginalId:"22")
		cancion22.save(flush:true)
		def cancion23 = new Cancion(author: 'Callejeros', name:'El ignorante', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (23).mp3', cancionOriginalId:"23")
		cancion23.save(flush:true)
		def cancion24 = new Cancion(author: 'Callejeros', name:'Ilusion', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (24).mp3', cancionOriginalId:"24")
		cancion24.save(flush:true)
		def cancion25 = new Cancion(author: 'Callejeros', name:'Algo peor, algo mejor', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (25).mp3', cancionOriginalId:"25")
		cancion25.save(flush:true)
		def cancion26 = new Cancion(author: 'Callejeros', name:'Durmiendo en la seccional', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (26).mp3', cancionOriginalId:"26")
		cancion26.save(flush:true)
		def cancion27 = new Cancion(author: 'Daddy yankee', name:'Limbo', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (27).mp3', cancionOriginalId:"27")
		cancion27.save(flush:true)
		def cancion28 = new Cancion(author: 'David bisbal', name:'Hasta el final', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (28).mp3', cancionOriginalId:"28")
		cancion28.save(flush:true)
		def cancion29 = new Cancion(author: 'Falsos profetas', name:'Cinco palabras', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (29).mp3', cancionOriginalId:"29")
		cancion29.save(flush:true)
		def cancion30 = new Cancion(author: 'Jesse y joy', name:'Con quien se queda el perro', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (30).mp3', cancionOriginalId:"30")
		cancion30.save(flush:true)
		def cancion31 = new Cancion(author: 'John lennon', name:'Stand by me', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (31).mp3', cancionOriginalId:"31")
		cancion31.save(flush:true)
		def cancion32 = new Cancion(author: 'Las pastillas del abuelo', name:'Hasta aca nos ayudo dios', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (32).mp3', cancionOriginalId:"32")
		cancion32.save(flush:true)
		def cancion33 = new Cancion(author: 'Las pastillas del abuelo', name:'Amar y envejecer', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (33).mp3', cancionOriginalId:"33")
		cancion33.save(flush:true)
		def cancion34 = new Cancion(author: 'Las pastillas del abuelo', name:'Candombe de resacas', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (34).mp3', cancionOriginalId:"34")
		cancion34.save(flush:true)
		def cancion35 = new Cancion(author: 'Las pastillas del abuelo', name:'Cambios de tiempo', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (35).mp3', cancionOriginalId:"35")
		cancion35.save(flush:true)
		def cancion36 = new Cancion(author: 'Las pastillas del abuelo', name:'Raton', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (36).mp3', cancionOriginalId:"36")
		cancion36.save(flush:true)
		def cancion37 = new Cancion(author: 'Las pastillas del abuelo', name:'Donde esconder tantas manos', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (37).mp3', cancionOriginalId:"37")
		cancion37.save(flush:true)
		def cancion38 = new Cancion(author: 'Las pastillas del abuelo', name:'Oportunistas', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (38).mp3', cancionOriginalId:"38")
		cancion38.save(flush:true)
		def cancion39 = new Cancion(author: 'Las pastillas del abuelo', name:'Me juego el corazon', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (39).mp3', cancionOriginalId:"39")
		cancion39.save(flush:true)
		def cancion40 = new Cancion(author: 'Leon gieco', name:'Solo le pido a dios', estrella:0,puntuacion:0, url:'http://localhost:80/Musica/pista (40).mp3', cancionOriginalId:"40")
		cancion40.save(flush:true)	
    }

	def destroy = {
    }
}
